### ISSUE TITLE
Users should not be asked year/city every invocation

### ISSUE THREAD

**Issue by TomOnTime** [devopsdays/devopsdays-cli#125]
Rather than asking the year and city for each command, it would be nice if they were read from $DOD_YEAR and $DOD_CITY; and only prompt the user if those aren't set.

Or maybe there  should be a .dodconfig file with these kind of settings. Though, that would probably suck for people maintaining multiple DOD sites.

**Comment by TomOnTime** [comment]
This was fixed in 4d1fd588382f00785c52d15cdfe55ea22461b789

**Comment by mattstratton** [comment]
I'm not sure why this issue got re-opened, but I'm pretty sure it's no longer valid.
