### ISSUE TITLE
Should give a "thing" more meaning

### ISSUE THREAD

**Issue by kmugrage** [devopsdays/devopsdays-cli#66]
Maybe just a string that says something like "things could be events, speakers, sponsors and more"

![image](https://user-images.githubusercontent.com/3209933/31133189-9fc2b462-a813-11e7-8463-c1e06cb656ae.png)

**Comment by kmugrage** [comment]
Ah, especially now that I typed 'devopsdays-cli add' and was surprised to not see event

**Comment by kmugrage** [comment]
For my clarity, first you create a thing and then you add the thing to another thing?

**Comment by mattstratton** [comment]
Fixed in 6c4fc1054d9c53c3d4020257bf48aea21e2df2b0
