### ISSUE TITLE
specify @ symbol or not when asking for Twitter handle

### ISSUE THREAD

**Issue by kmugrage** [devopsdays/devopsdays-cli#68]
specify @ symbol or not when asking for Twitter handle

**Comment by mattstratton** [comment]
Yeah, as you can see in https://github.com/devopsdays/devopsdays-cli/blob/master/helpers/validate_field.go#L27-L31, we actually do not want the @ symbol.

There are a couple things we could do:

1) Make sure the prompt says "enter the twitter handle without the @ symbol"
or
2) Allow it with or without, and then just strip it ourselves. 

Option 2 seems best.

**Comment by kmugrage** [comment]
yeah, 2 seems best
