### ISSUE TITLE
! separators made me think it didn't work

### ISSUE THREAD

**Issue by kmugrage** [devopsdays/devopsdays-cli#69]
I don't know why exactly, but I interpreted this as it blowing up when in fact it worked.

![image](https://user-images.githubusercontent.com/3209933/31133561-c270c7c8-a814-11e7-80c2-4351367ebe21.png)

**Comment by mattstratton** [comment]
Ha. I think I told you not to run the create event stuff. That's old code :)

**Comment by kmugrage** [comment]
I blame reading comprehension issues on cold meds.
