### ISSUE TITLE
Speaker not created

### ISSUE THREAD

**Issue by kmugrage** [devopsdays/devopsdays-cli#90]
The image is added but no other data is created. This is using latest master from https://github.com/devopsdays/devopsdays-web. 

![image](https://user-images.githubusercontent.com/3209933/31240803-b799173a-a9b6-11e7-9eff-eff1e9304571.png)

**Comment by mattstratton** [comment]
Are you running this inside the root of devopsdays-web from a recent pull? Just want to try to reproduce.
